In [25]:
import talib
import pandas as pd

In [26]:
# DataFrameがdfという変数に格納されているとします
df = pd.read_pickle('./data/df_rates_3H.pkl')
df

,time,open,high,low,close,tick_volume,spread,real_volume
0,1971-01-04 00:00:00,357.730,357.730,357.730,357.730,1,50,0
1,1971-01-05 00:00:00,357.810,357.810,357.810,357.810,1,50,0
2,1971-01-06 00:00:00,357.860,357.860,357.860,357.860,1,50,0
3,1971-01-07 00:00:00,357.870,357.870,357.870,357.870,1,50,0
4,1971-01-08 00:00:00,357.820,357.820,357.820,357.820,1,50,0
...,...,...,...,...,...,...,...,...
60252,2024-07-30 03:00:00,153.827,154.241,153.607,154.012,21106,23,0
60253,2024-07-30 06:00:00,154.012,154.758,153.967,154.655,21660,23,0
60254,2024-07-30 09:00:00,154.655,155.209,154.589,154.657,30640,23,0
60255,2024-07-30 12:00:00,154.657,154.926,154.655,154.879,15230,23,0
60256,2024-07-30 15:00:00,154.877,155.014,154.284,154.548,23568,23,0

In [27]:
# datetune列の内容をDatetime型かつaware(UTC)で、"datetime_utc"列に入れる 
df["time_jst"] = pd.to_datetime(df["time"], utc=True) 
# JSTに変換したデータを"datetime_jst"列に入れる
df["time_jst"] = df["time_jst"].dt.tz_convert('Asia/Tokyo')
df

,time,open,high,low,close,tick_volume,spread,real_volume,time_jst
0,1971-01-04 00:00:00,357.730,357.730,357.730,357.730,1,50,0,1971-01-04 09:00:00+09:00
1,1971-01-05 00:00:00,357.810,357.810,357.810,357.810,1,50,0,1971-01-05 09:00:00+09:00
2,1971-01-06 00:00:00,357.860,357.860,357.860,357.860,1,50,0,1971-01-06 09:00:00+09:00
3,1971-01-07 00:00:00,357.870,357.870,357.870,357.870,1,50,0,1971-01-07 09:00:00+09:00
4,1971-01-08 00:00:00,357.820,357.820,357.820,357.820,1,50,0,1971-01-08 09:00:00+09:00
...,...,...,...,...,...,...,...,...,...
60252,2024-07-30 03:00:00,153.827,154.241,153.607,154.012,21106,23,0,2024-07-30 12:00:00+09:00
60253,2024-07-30 06:00:00,154.012,154.758,153.967,154.655,21660,23,0,2024-07-30 15:00:00+09:00
60254,2024-07-30 09:00:00,154.655,155.209,154.589,154.657,30640,23,0,2024-07-30 18:00:00+09:00
60255,2024-07-30 12:00:00,154.657,154.926,154.655,154.879,15230,23,0,2024-07-30 21:00:00+09:00
60256,2024-07-30 15:00:00,154.877,155.014,154.284,154.548,23568,23,0,2024-07-31 00:00:00+09:00

In [28]:
# RSI(7)の計算
rsi_val = talib.RSI(df['close'], timeperiod=7)
# Stochastics(14, 3, 3)の計算
slowk, slowd = talib.STOCH(df['high'], df['low'], df['close'], fastk_period=14, slowk_period=3, slowk_matype=0, slowd_period=3, slowd_matype=0)
# MACD(12, 26, 9)の計算
macd, macdsignal, macdhist = talib.MACD(df['close'], fastperiod=12, slowperiod=26, signalperiod=9)
# ADR(7)の計算
adr = talib.SMA(df['high'], timeperiod=7) - talib.SMA(df['low'], timeperiod=7)

# 結果をDataFrameに追加
df['RSI'] = rsi_val
df['Stoch_K'] = slowk
df['Stoch_D'] = slowd
df['MACD'] = macd
df['MACD_Signal'] = macdsignal
df['MACD_Hist'] = macdhist
df['ADR'] = adr
df

,time,open,high,low,close,tick_volume,spread,real_volume,time_jst,RSI,Stoch_K,Stoch_D,MACD,MACD_Signal,MACD_Hist,ADR
0,1971-01-04 00:00:00,357.730,357.730,357.730,357.730,1,50,0,1971-01-04 09:00:00+09:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1971-01-05 00:00:00,357.810,357.810,357.810,357.810,1,50,0,1971-01-05 09:00:00+09:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1971-01-06 00:00:00,357.860,357.860,357.860,357.860,1,50,0,1971-01-06 09:00:00+09:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1971-01-07 00:00:00,357.870,357.870,357.870,357.870,1,50,0,1971-01-07 09:00:00+09:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1971-01-08 00:00:00,357.820,357.820,357.820,357.820,1,50,0,1971-01-08 09:00:00+09:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60252,2024-07-30 03:00:00,153.827,154.241,153.607,154.012,21106,23,0,2024-07-30 12:00:00+09:00,55.105870,54.988399,56.103377,-0.163968,-0.272963,0.108994,0.402143
60253,2024-07-30 06:00:00,154.012,154.758,153.967,154.655,21660,23,0,2024-07-30 15:00:00+09:00,69.600305,66.778068,58.795835,-0.089613,-0.236293,0.146680,0.404000
60254,2024-07-30 09:00:00,154.655,155.209,154.589,154.657,30640,23,0,2024-07-30 18:00:00+09:00,69.635879,75.854124,65.873530,-0.030176,-0.195070,0.164893,0.449000
60255,2024-07-30 12:00:00,154.657,154.926,154.655,154.879,15230,23,0,2024-07-30 21:00:00+09:00,73.631819,84.709236,75.780476,0.034444,-0.149167,0.183611,0.419143
60256,2024-07-30 15:00:00,154.877,155.014,154.284,154.548,23568,23,0,2024-07-31 00:00:00+09:00,59.915972,76.674225,79.079195,0.058275,-0.107679,0.165954,0.491714

In [29]:
# バーの色を決定
df['GreenBar'] = (df['RSI'] > 50) & (df['Stoch_K'] > 50) & (df['MACD_Hist'] > 0)
df['RedBar'] = (df['RSI'] < 50) & (df['Stoch_K'] < 50) & (df['MACD_Hist'] < 0)
df['BlackBar'] = ~(df['GreenBar'] | df['RedBar'])

In [30]:
df.tail(30)

,time,open,high,low,close,tick_volume,spread,real_volume,time_jst,RSI,Stoch_K,Stoch_D,MACD,MACD_Signal,MACD_Hist,ADR,GreenBar,RedBar,BlackBar
60227,2024-07-25 00:00:00,153.842,153.944,153.494,153.907,10447,23,0,2024-07-25 09:00:00+09:00,29.851398,21.400712,15.212052,-0.856934,-0.685693,-0.171241,0.692143,False,True,False
60228,2024-07-25 03:00:00,153.907,153.961,152.507,152.630,33786,23,0,2024-07-25 12:00:00+09:00,18.207940,16.223332,17.581584,-0.953104,-0.739175,-0.213928,0.766000,False,True,False
60229,2024-07-25 06:00:00,152.630,152.964,152.220,152.732,24026,23,0,2024-07-25 15:00:00+09:00,21.076601,12.969620,16.864555,-1.009452,-0.793231,-0.216221,0.790714,False,True,False
60230,2024-07-25 09:00:00,152.730,152.928,151.929,152.697,38529,23,0,2024-07-25 18:00:00+09:00,20.784772,11.483630,13.558861,-1.044887,-0.843562,-0.201325,0.807429,False,True,False
60231,2024-07-25 12:00:00,152.700,152.734,152.080,152.714,23790,23,0,2024-07-25 21:00:00+09:00,21.401466,16.846419,13.766557,-1.059387,-0.886727,-0.172660,0.741143,False,True,False
60232,2024-07-25 15:00:00,152.715,154.185,152.541,153.634,47408,23,0,2024-07-26 00:00:00+09:00,47.303276,26.641392,18.323814,-0.985283,-0.906438,-0.078845,0.891286,False,True,False
60233,2024-07-25 18:00:00,153.634,154.308,153.623,154.024,32313,23,0,2024-07-26 03:00:00+09:00,54.688266,37.708693,27.065502,-0.884886,-0.902128,0.017242,0.947143,False,False,True
60234,2024-07-25 21:00:00,154.023,154.045,153.762,153.911,16628,23,0,2024-07-26 06:00:00+09:00,52.214721,50.926979,38.425688,-0.805157,-0.882734,0.077577,0.923286,True,False,False
60235,2024-07-26 00:00:00,153.924,153.985,153.369,153.693,11805,23,0,2024-07-26 09:00:00+09:00,47.390352,56.439328,48.358334,-0.750906,-0.856368,0.105462,0.803571,False,False,True
60236,2024-07-26 03:00:00,153.693,154.133,153.356,153.911,29719,23,0,2024-07-26 12:00:00+09:00,52.509536,61.260917,56.209075,-0.682454,-0.821585,0.139131,0.808286,True,False,False
60237,2024-07-26 06:00:00,153.910,153.910,153.494,153.634,14712,23,0,2024-07-26 15:00:00+09:00,45.890054,65.476098,61.058781,-0.643143,-0.785897,0.142754,0.725000,False,False,True
60238,2024-07-26 09:00:00,153.633,154.424,153.533,154.292,30469,23,0,2024-07-26 18:00:00+09:00,59.899681,77.511020,68.082678,-0.552525,-0.739222,0.186698,0.758857,True,False,False
60239,2024-07-26 12:00:00,154.293,154.728,154.024,154.601,22632,23,0,2024-07-26 21:00:00+09:00,64.881267,87.280284,76.755801,-0.450581,-0.681494,0.230913,0.624571,True,False,False
60240,2024-07-26 15:00:00,154.601,154.718,153.081,153.492,43185,23,0,2024-07-27 00:00:00+09:00,42.680459,82.004485,82.265263,-0.454043,-0.636004,0.181961,0.760571,False,False,True
60241,2024-07-26 18:00:00,153.494,153.870,153.485,153.723,20938,23,0,2024-07-27 03:00:00+09:00,47.080834,71.799452,80.361407,-0.433154,-0.595434,0.162280,0.775143,False,False,True
60242,2024-07-26 21:00:00,153.724,153.819,153.666,153.764,9520,23,0,2024-07-27 06:00:00+09:00,47.908908,61.831607,71.878515,-0.408581,-0.558064,0.149482,0.709000,False,False,True
60243,2024-07-29 00:00:00,153.632,154.203,153.571,154.136,12583,23,0,2024-07-29 09:00:00+09:00,55.311119,69.501012,67.710690,-0.354998,-0.517450,0.162453,0.688286,True,False,False
60244,2024-07-29 03:00:00,154.141,154.344,153.004,153.408,35961,23,0,2024-07-29 12:00:00+09:00,41.761918,64.853258,65.395292,-0.367045,-0.487369,0.120325,0.820286,False,False,True
60245,2024-07-29 06:00:00,153.409,153.685,153.294,153.376,21860,23,0,2024-07-29 15:00:00+09:00,41.243804,55.726934,63.360402,-0.374853,-0.464866,0.090013,0.748857,False,False,True
60246,2024-07-29 09:00:00,153.376,153.910,153.132,153.680,32117,23,0,2024-07-29 18:00:00+09:00,48.346383,42.514117,54.364770,-0.352448,-0.442382,0.089934,0.759429,False,False,True
60247,2024-07-29 12:00:00,153.677,153.884,153.579,153.823,21934,23,0,2024-07-29 21:00:00+09:00,51.559872,41.632364,46.624472,-0.319470,-0.417800,0.098330,0.569143,False,False,True
60248,2024-07-29 15:00:00,153.826,154.200,153.720,154.038,33003,23,0,2024-07-30 00:00:00+09:00,56.325828,48.897912,44.348131,-0.272842,-0.388808,0.115967,0.582714,False,False,True
60249,2024-07-29 18:00:00,154.037,154.083,153.861,153.993,19162,23,0,2024-07-30 03:00:00+09:00,55.004342,54.949729,48.493335,-0.236789,-0.358404,0.121615,0.592571,True,False,False
60250,2024-07-29 21:00:00,153.992,154.046,153.950,154.017,9552,23,0,2024-07-30 06:00:00+09:00,55.651749,58.700696,54.182779,-0.203930,-0.327510,0.123579,0.516000,True,False,False
60251,2024-07-30 00:00:00,154.004,154.057,153.757,153.827,7754,23,0,2024-07-30 09:00:00+09:00,49.123657,54.621036,56.090487,-0.191019,-0.300212,0.109193,0.367429,False,False,True
60252,2024-07-30 03:00:00,153.827,154.241,153.607,154.012,21106,23,0,2024-07-30 12:00:00+09:00,55.105870,54.988399,56.103377,-0.163968,-0.272963,0.108994,0.402143,True,False,False
60253,2024-07-30 06:00:00,154.012,154.758,153.967,154.655,21660,23,0,2024-07-30 15:00:00+09:00,69.600305,66.778068,58.795835,-0.089613,-0.236293,0.146680,0.404000,True,False,False
60254,2024-07-30 09:00:00,154.655,155.209,154.589,154.657,30640,23,0,2024-07-30 18:00:00+09:00,69.635879,75.854124,65.873530,-0.030176,-0.195070,0.164893,0.449000,True,False,False
60255,2024-07-30 12:00:00,154.657,154.926,154.655,154.879,15230,23,0,2024-07-30 21:00:00+09:00,73.631819,84.709236,75.780476,0.034444,-0.149167,0.183611,0.419143,True,False,False
60256,2024-07-30 15:00:00,154.877,155.014,154.284,154.548,23568,23,0,2024-07-31 00:00:00+09:00,59.915972,76.674225,79.079195,0.058275,-0.107679,0.165954,0.491714,True,False,False

In [31]:
# ストップロスと利益目標の計算
stop_loss_multiple = 1.5
profit_target_multiple = 3.0

df['LongStopLimit'] = df['high'] + 0.01
df['LongProfitTarget'] = df['high'] + (profit_target_multiple * df['ADR'])
df['LongStopLoss'] = df['high'] - (stop_loss_multiple * df['ADR'])

df['ShortStopLimit'] = df['low'] - 0.01
df['ShortProfitTarget'] = df['low'] - (profit_target_multiple * df['ADR'])
df['ShortStopLoss'] = df['low'] + (stop_loss_multiple * df['ADR'])

df

,time,open,high,low,close,tick_volume,spread,real_volume,time_jst,RSI,...,ADR,GreenBar,RedBar,BlackBar,LongStopLimit,LongProfitTarget,LongStopLoss,ShortStopLimit,ShortProfitTarget,ShortStopLoss
0,1971-01-04 00:00:00,357.730,357.730,357.730,357.730,1,50,0,1971-01-04 09:00:00+09:00,NaN,...,NaN,False,False,True,357.740,NaN,NaN,357.720,NaN,NaN
1,1971-01-05 00:00:00,357.810,357.810,357.810,357.810,1,50,0,1971-01-05 09:00:00+09:00,NaN,...,NaN,False,False,True,357.820,NaN,NaN,357.800,NaN,NaN
2,1971-01-06 00:00:00,357.860,357.860,357.860,357.860,1,50,0,1971-01-06 09:00:00+09:00,NaN,...,NaN,False,False,True,357.870,NaN,NaN,357.850,NaN,NaN
3,1971-01-07 00:00:00,357.870,357.870,357.870,357.870,1,50,0,1971-01-07 09:00:00+09:00,NaN,...,NaN,False,False,True,357.880,NaN,NaN,357.860,NaN,NaN
4,1971-01-08 00:00:00,357.820,357.820,357.820,357.820,1,50,0,1971-01-08 09:00:00+09:00,NaN,...,NaN,False,False,True,357.830,NaN,NaN,357.810,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60252,2024-07-30 03:00:00,153.827,154.241,153.607,154.012,21106,23,0,2024-07-30 12:00:00+09:00,55.105870,...,0.402143,True,False,False,154.251,155.447429,153.637786,153.597,152.400571,154.210214
60253,2024-07-30 06:00:00,154.012,154.758,153.967,154.655,21660,23,0,2024-07-30 15:00:00+09:00,69.600305,...,0.404000,True,False,False,154.768,155.970000,154.152000,153.957,152.755000,154.573000
60254,2024-07-30 09:00:00,154.655,155.209,154.589,154.657,30640,23,0,2024-07-30 18:00:00+09:00,69.635879,...,0.449000,True,False,False,155.219,156.556000,154.535500,154.579,153.242000,155.262500
60255,2024-07-30 12:00:00,154.657,154.926,154.655,154.879,15230,23,0,2024-07-30 21:00:00+09:00,73.631819,...,0.419143,True,False,False,154.936,156.183429,154.297286,154.645,153.397571,155.283714
60256,2024-07-30 15:00:00,154.877,155.014,154.284,154.548,23568,23,0,2024-07-31 00:00:00+09:00,59.915972,...,0.491714,True,False,False,155.024,156.489143,154.276429,154.274,152.808857,155.021571

In [32]:
# 取引シグナルの生成
df['LongEntry'] = (df['GreenBar'].astype(bool)) & (~df['GreenBar'].shift(1).astype(bool))
df['ShortEntry'] = (df['RedBar'].astype(bool)) & (~df['RedBar'].shift(1).astype(bool))
df['LongExit'] = (df['BlackBar'].astype(bool)) | (df['RedBar'].astype(bool))
df['ShortExit'] = (df['BlackBar'].astype(bool)) | (df['GreenBar'].astype(bool))
df

,time,open,high,low,close,tick_volume,spread,real_volume,time_jst,RSI,...,LongStopLimit,LongProfitTarget,LongStopLoss,ShortStopLimit,ShortProfitTarget,ShortStopLoss,LongEntry,ShortEntry,LongExit,ShortExit
0,1971-01-04 00:00:00,357.730,357.730,357.730,357.730,1,50,0,1971-01-04 09:00:00+09:00,NaN,...,357.740,NaN,NaN,357.720,NaN,NaN,False,False,True,True
1,1971-01-05 00:00:00,357.810,357.810,357.810,357.810,1,50,0,1971-01-05 09:00:00+09:00,NaN,...,357.820,NaN,NaN,357.800,NaN,NaN,False,False,True,True
2,1971-01-06 00:00:00,357.860,357.860,357.860,357.860,1,50,0,1971-01-06 09:00:00+09:00,NaN,...,357.870,NaN,NaN,357.850,NaN,NaN,False,False,True,True
3,1971-01-07 00:00:00,357.870,357.870,357.870,357.870,1,50,0,1971-01-07 09:00:00+09:00,NaN,...,357.880,NaN,NaN,357.860,NaN,NaN,False,False,True,True
4,1971-01-08 00:00:00,357.820,357.820,357.820,357.820,1,50,0,1971-01-08 09:00:00+09:00,NaN,...,357.830,NaN,NaN,357.810,NaN,NaN,False,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60252,2024-07-30 03:00:00,153.827,154.241,153.607,154.012,21106,23,0,2024-07-30 12:00:00+09:00,55.105870,...,154.251,155.447429,153.637786,153.597,152.400571,154.210214,True,False,False,True
60253,2024-07-30 06:00:00,154.012,154.758,153.967,154.655,21660,23,0,2024-07-30 15:00:00+09:00,69.600305,...,154.768,155.970000,154.152000,153.957,152.755000,154.573000,False,False,False,True
60254,2024-07-30 09:00:00,154.655,155.209,154.589,154.657,30640,23,0,2024-07-30 18:00:00+09:00,69.635879,...,155.219,156.556000,154.535500,154.579,153.242000,155.262500,False,False,False,True
60255,2024-07-30 12:00:00,154.657,154.926,154.655,154.879,15230,23,0,2024-07-30 21:00:00+09:00,73.631819,...,154.936,156.183429,154.297286,154.645,153.397571,155.283714,False,False,False,True
60256,2024-07-30 15:00:00,154.877,155.014,154.284,154.548,23568,23,0,2024-07-31 00:00:00+09:00,59.915972,...,155.024,156.489143,154.276429,154.274,152.808857,155.021571,False,False,False,True